# on narval
cd /home/jflucier/projects/def-jflucier/programs/
git clone https://github.com/steineggerlab/foldseek.git
cd foldseek
ml StdEnv/2023
ml gcc/12.3 openmpi/4.1.5 cuda/12.2 rust/1.76.0

# build on compute node with gpu
cmake -DCMAKE_INSTALL_PREFIX=$PWD -DCMAKE_BUILD_TYPE=Release -DENABLE_CUDA=1 -DCUDAToolkit_ROOT=/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Core/cudacore/12.2.2 .
make -j 8
make install

### test
mkdir test
cd test

#!/bin/bash

#SBATCH --job-name=test
#SBATCH -D /home/jflucier/projects/def-jflucier/programs/foldseek/test
#SBATCH -o /home/jflucier/projects/def-jflucier/programs/foldseek/test/slurm-%A_%a.out
#SBATCH --account=def-jflucier
#SBATCH --time=1:00:00
#SBATCH --cpus-per-task=20
#SBATCH --gres=gpu:1
#SBATCH --mem=80G

cd /home/jflucier/projects/def-jflucier/programs/foldseek/test

echo "loading env"
ml gcc/12.3 openmpi/4.1.5 cuda/12.2 rust/1.76.0

echo "running foldseek on test data"
foldseek easy-search --threads 20 --gpu 1 \
../example/d1asha_ \
/cvmfs/bio.data.computecanada.ca/content/databases/Core/alphafold2_dbs/2023_07 \
aln.m8 tmpFolder

echo "foldseek done"