
- name: npm run build
  become: no
  ansible.builtin.command:
    cmd: "npm run build"
    chdir: "{{spa_dir}}"
  register: script_output
  delegate_to: localhost


- name: copy bundles
  ansible.builtin.copy:
    src: "{{item}}"
    dest: "{{dst}}"
    owner: "{{service_user}}"
    group: "{{service_user}}"
  with_fileglob:
    - "{{src}}"