
- name: apt installs
  become: yes
  ansible.builtin.apt:
    pkg:
    - sqlite3

- name: init auth db if not exists
  ansible.builtin.shell: "export PYTHONPATH=/web-gasket/WebGasket && /web-gasket_venv/bin/python3 /web-gasket/WebGasket/web_gasket/auth.py init-db {{wg_auth_db}}"
  become: yes
  become_user: "{{os_user}}"
  args:
    creates: "/home/{{os_user}}/web-gasket-auth.db"

- name: add or create admin account {{admin_email}}
  ansible.builtin.shell: "export PYTHONPATH=/web-gasket/WebGasket && /web-gasket_venv/bin/python3 /web-gasket/WebGasket/web_gasket/auth.py add-user {{wg_auth_db}} {{admin_email}}"
  become: yes
  become_user: "{{os_user}}"


- name: create dirs
  become: yes
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
    owner: "{{os_user}}"
    group: "{{os_user}}"
  loop: "{{ work_dirs }}"


- ansible.builtin.copy:
    dest: "/home/{{os_user}}/add-user.sh"
    mode: u=rwx,g=r,o=r
    content: |
          #!/bin/bash
          export PYTHONPATH=/web-gasket/WebGasket
          /web-gasket_venv/bin/python3 /web-gasket/WebGasket/web_gasket/auth.py add-user {{wg_auth_db}} $1