
---

- hosts: [web_gasket]
  vars:
    wg_upload_dir: "{{web_gasket_data_dir}}/.tmp-upload"
    wg_instances_dir: "{{web_gasket_data_dir}}/pipeline-instances"
    wg_auth_db: "/home/web-gasket/web-gasket-auth.db"
    wg_log_dir: "/var/log/web-gasket"
  become: yes
  gather_facts: no
  roles:
    - role: python_service
      when: True
      vars:
        service_name: "web-gasket"
        log_dir: "{{wg_log_dir}}"
        git_repo: "git@github.com:jflucier/Marechal_pipelines.git"
        branch: "{{git_branch}}"
        reqs: "/web-gasket/requirements-web-gasket.txt"
        env_vars:
          - "PYTHONPATH=/web-gasket/DryPipe:/web-gasket/WebGasket:/web-gasket/DPfold"
          - "PIPELINE_INSTANCES_DIR={{wg_instances_dir}}"
          - "WEB_GASKET_TEMP_FILE_UPLOAD_DIR={{wg_upload_dir}}"
          - "WEB_SESSION_KEY='{{web_session_key}}'"
          - "LOGGING_CONF=/web-gasket/log-conf.json"
          - "USER_AUTH_DB={{wg_auth_db}}"
          - "WEB_GASKET_LOG_FILE={{log_dir}}/app.log"
          - "WEB_APP_PORT=8000"
          - "USE_CC_ROBOT={{USE_CC_ROBOT}}"
          - "cc_username={{cc_username}}"
          - "CC_ALLOCATIONS_FILE=/home/web-gasket/cc_allocs.json"
          - "DRYPIPE_DEBUG=True"

    - role: web_gasket
      when: True
      vars:
        os_user: "web-gasket"
        work_dirs:
          - "{{web_gasket_data_dir}}"
          - "{{wg_upload_dir}}"
          - "{{wg_instances_dir}}/dp-fold"

    - role: javascript_spa
      when: True
      vars:
        service_user: web-gasket
        src: "../web-ui/build"
        dst: /web-gasket/web-ui/build
        spa_dir: "../web-ui"

  handlers:
    - name: restart drypipe
      ansible.builtin.systemd:
        name: "drypipe"
        daemon_reload: yes
        enabled: true
        state: restarted

    - name: restart web-gasket
      ansible.builtin.systemd:
        name: "web-gasket"
        daemon_reload: yes
        enabled: true
        state: restarted

  tasks:
    - name: upload cc_allocs.json
      ansible.builtin.copy:
        dest: "/home/web-gasket/cc_allocs.json"
        src: "cc_allocs.json"
        owner: "web-gasket"
        group: "web-gasket"
        mode: u=rw,g=r,o=r

    - name: "create drypipe service file"
      ansible.builtin.copy:
        dest: "/etc/systemd/system/drypipe.service"
        content: |
                 [Unit]
                 After=network.target 
          
                 [Service]
                 TimeoutStopSec=2
                 LimitNOFILE=2072576
                 User=web-gasket
                 Group=web-gasket
                 WorkingDirectory=/home/web-gasket
                 EnvironmentFile=/home/web-gasket/env
                 
                 ExecStart=/web-gasket_venv/bin/python3 /web-gasket/DryPipe/dry_pipe/cli.py service --config-generator=dpfold.pipeline_conf:gen_conf --log-conf=/home/web-gasket/active-drypipe-log-conf.json 
          
                 [Install]
                 WantedBy=multi-user.target
      notify: "restart drypipe"

    - name: "create web-gasket service file"
      ansible.builtin.copy:
        dest: "/etc/systemd/system/web-gasket.service"
        content: |
                 [Unit]
                 After=network.target
          
                 [Service]
                 TimeoutStopSec=1
                 LimitNOFILE=2048
                 User=web-gasket
                 Group=web-gasket
                 WorkingDirectory=/home/web-gasket
                 EnvironmentFile=/home/web-gasket/env
                 AmbientCapabilities=CAP_NET_BIND_SERVICE
                 
                 ExecStart=/web-gasket_venv/bin/uvicorn dpfold.server:init_app --workers=4 --port=80 --host=0.0.0.0
          
                 # Danger: for debugging only: the logs will be owned by root, must be deleted manually removed
                 # StandardOutput=file:/var/log/out-err.log
                 # StandardError=file:/var/log/out-err.log
          
                 [Install]
                 WantedBy=multi-user.target
      notify: "restart web-gasket"


    - ansible.builtin.copy:
        dest: "/home/web-gasket/drypipe-log-conf.json"
        content: |
          {
            "version": 1,
            "formatters": {
              "simple": {
                "format": "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
              }
            },
            "handlers": {
              "logfile": {
                  "class": "logging.handlers.RotatingFileHandler",
                  "formatter": "simple",
                  "filename": "{{wg_log_dir}}/drypipe-service.log",
                  "maxBytes": 10485760,
                  "backupCount": 3
              }
            },
            "root": {
              "level": "DEBUG",
              "handlers": ["logfile"]
            },
            "dry_pipe": {
               "level": "DEBUG",
               "handlers": ["logfile"],
               "propagate": 0
            }
          }

    - name: create a symbolic link to drypipe-log-conf.json
      ansible.builtin.file:
        src: /home/web-gasket/drypipe-log-conf.json
        dest: /home/web-gasket/active-drypipe-log-conf.json
        owner: web-gasket
        group: web-gasket
        state: link
